- Developer:
    - Github/Awesome Self-Hosted:
        - abbr: SH
          href: https://github.com/awesome-selfhosted/awesome-selfhosted
    - Reddit/Awesome Self-Hosted:
        - abbr: SH
          href: https://reddit.com/r/selfhosted/
    - Traversy Media - Javascript Course:
        - abbr: JS
          href: https://traversymedia.com/products/modern-javascript-from-the-beginning-2-0

- Personal:
    - Github:
        - abbr: GH
          href: https://github.com/DaveLuhman
    - Reddit:
        - icon: reddit.png
          href: https://reddit.com/
    - YouTube:
        - abbr: YT
          href: https://youtube.com/

- Madison College:
    - Service Now:
        - abbr: SN
          href: https://madisoncollege.service-now.com/
    - WolfNet:
        - abbr: WN
          href: https://apps7.madisoncollege.edu/employee-landing
    - Warranty Submit Form:
        - abbr: WS
          href: https://forms.office.com/Pages/ResponsePage.aspx?id=RgHwM8xv6Um1aHiWswadRPsYHl8r-QlApWY_i0iFQ65URTZZSzI0NjdZSEtCTk1LRDlRSTdXMEhUTC4u
    - Warranty Return Form:
        - abbr: WR
          href: https://forms.office.com/Pages/ResponsePage.aspx?id=RgHwM8xv6Um1aHiWswadRPsYHl8r-QlApWY_i0iFQ65UNlhJMllOSkYwSEVQV1I1VU0xOVlLV0RXTy4u