- Published:
      - Public Website:
            href: http://ado.software/
            description: Pubilc Facing Website
      - Blog:
            href: http://blog.ado.software/
            description: My blog
      - TimeKeeper Front-End:
            href: https://time.forwardelectric.com/
            description: TimeKeeper Published Front-End
      - Traccar:
            href: https://gps.luhman.website:8082
            description: Hosted Fleet Monitoring Service

- Hosted Services:
      - EasyPanel:
            href: http://easypanel.ep.ado.software
            description: Easypanel Orchestration Environment.
      - ToolKeeper:
            href: http://toolkeeper.ep.ado.software/
            description: Current Master Release Build of ToolKeeper

- VPN Only Systems:
      - VMhost:
            href: https://vmhost.ep.ado.software:8006
            description: Core Proxmox Host
      - DC Backup Server:
            href: https://10.20.30.4:8007
            description: Backup Server at the DC
      - Offsite VMHost:
            href: https://10.11.12.11:8006
            description: Offsite Proxmox Host
      - Offsite Backups:
            href: https://10.11.12.12:8007
      - Development Proxmox Node:
            href: https://10.10.10.111:8006
            description: Proxmox Host at home

- Service Providers:
      - Wasabi Object Storage:
            description: Object storage location for database backups
            href: http://console.wasabisys.com
      - LemonSqueezy:
            description: SaaS Payment Provider
            href: https://lemonsqueezy.com
      - Hologram:
            description: IoT Cellular Service Provider
            href: https://dashboard.hologram.io
      - NameCheap:
            description: Domain Registrar
            href: https://www.namecheap.com
      - Cloudflare:
            description: DNS and CDN Provider
            href: https://dash.cloudflare.com